import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { SiHasura, SiNextdotjs, SiGraphql, SiPostgresql } from 'react-icons/si';
export default function Home(navigation) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className=' flex flex-wrap items-center justify-center p-2'>
          <SiHasura size="2em" color="#8C7A64" className="mt-2 mr-2" />
          <SiNextdotjs size="2em" color="#8C7A64" className="mt-2 mr-2" />
          <SiGraphql size="2em" color="#8C7A64" className="mt-2 mr-2" />
          <SiPostgresql size="2em" color="#8C7A64" className="mt-2 mr-2" />
        </div>

        {<div className=' flex flex-wrap items-center justify-evenly p-2 text-teal-800 font-bold text-2xl'>
          {console.log(navigation)}
          {navigation.navigation.map((nav) => (
            <div key={nav.id}>{nav.name}</div>
          ))}

        </div>}


        <h1 className=' text-center'>
          Hasura with Nextjs
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const options = {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-hasura-admin-secret': process.env.HASURA_ADMIN_SECRET,
      // Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    },
    body: JSON.stringify({
      query: `query fetchNavigation {
        navigation {
          id
          name
        }
      }
      
      `,
      variables: {},
      operationName: "fetchNavigation",

    })
  }
  const fetchResponse = await fetch('https://ebartanhasuranextjs.hasura.app/v1/graphql', options)
  const fetchJson = await fetchResponse.json()
  console.log(fetchJson.data.navigation)
  const navigation = fetchJson.data.navigation
  return {

    props: { navigation: navigation }
  }
}